### ISSUE TITLE
NCMEC fetch failing on recent entries

### ISSUE THREAD

**Issue by aokolish** [facebook/ThreatExchange#1225]
We're using the CLI to fetch entries from NCMEC using version `1.0.2` and it's failing with error code 3. It looks like something is null that you don't expect to be null.

```shell
$ TX_NCMEC_CREDENTIALS=user:pass threatexchange -v fetch --only-collab ncmec --skip-index-rebuild
2022-12-05 11:56:43,025 I] Fetching all sample's configs
2022-12-05 11:56:43,025 I] Fetching all local_file's configs
2022-12-05 11:56:43,025 I] Fetching all stop_ncii's configs
2022-12-05 11:56:43,025 I] Fetching all ncmec's configs
2022-12-05 11:59:18,587 I] NCMEC API est 3227496 is over max fetch, duration reduced @2022-12-02T20:06:59Z (2.66 days)
[ncmec] ncmec - failed to fetch!
2022-12-05 11:59:23,047 E] Failed to fetch ncmec
Traceback (most recent call last):
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/cli/fetch_cmd.py", line 200, in execute_for_collab
    for delta in it:
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/impl/ncmec_api.py", line 277, in fetch_iter
    for i, entry in enumerate(
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 369, in get_entries_iter
    result = self.get_entries(
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 355, in get_entries
    return GetEntriesResponse.from_xml(_XMLWrapper(response), int(time.time()))
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 184, in from_xml
    updates.extend(NCMECEntryUpdate.from_xml(c) for c in content_xml)
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 184, in <genexpr>
    updates.extend(NCMECEntryUpdate.from_xml(c) for c in content_xml)
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 139, in from_xml
    fingerprints={x.tag: x.text for x in xml.maybe("fingerprints")},
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 139, in <dictcomp>
    fingerprints={x.tag: x.text for x in xml.maybe("fingerprints")},
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 72, in text
    return nullthrows(self.element.text)
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 36, in nullthrows
    assert v is not None
AssertionError
2022-12-05 11:59:47,254 I] Fetching all fb_threatexchange's configs
Some collabs had errors!
```

I tested using version 1.0.7 and the stack trace looks similar to me:

```shell
$ threatexchange --version
1.0.7
$ TX_NCMEC_CREDENTIALS=user:pass threatexchange -v fetch --only-collab ncmec --skip-index-rebuild
2022-12-05 12:06:06,568 I] Fetching all sample's configs
2022-12-05 12:06:06,569 I] Fetching all local_file's configs
2022-12-05 12:06:06,569 I] Fetching all stop_ncii's configs
2022-12-05 12:06:06,569 I] Fetching all ncmec's configs
2022-12-05 12:08:48,680 I] NCMEC API est 3227503 is over max fetch, duration reduced @2022-12-02T20:06:59Z (2.67 days)
[ncmec] ncmec - failed to fetch!
2022-12-05 12:08:51,712 E] Failed to fetch ncmec
Traceback (most recent call last):
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/cli/fetch_cmd.py", line 200, in execute_for_collab
    for delta in it:
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/impl/ncmec_api.py", line 277, in fetch_iter
    for i, entry in enumerate(
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 378, in get_entries_iter
    result = self.get_entries(
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 364, in get_entries
    return GetEntriesResponse.from_xml(_XMLWrapper(response), int(time.time()))
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 184, in from_xml
    updates.extend(NCMECEntryUpdate.from_xml(c) for c in content_xml)
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 184, in <genexpr>
    updates.extend(NCMECEntryUpdate.from_xml(c) for c in content_xml)
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 139, in from_xml
    fingerprints={x.tag: x.text for x in xml.maybe("fingerprints")},
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 139, in <dictcomp>
    fingerprints={x.tag: x.text for x in xml.maybe("fingerprints")},
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 72, in text
    return nullthrows(self.element.text)
  File "/Users/alex.okolish/.pyenv/versions/3.8.12/envs/ccs/lib/python3.8/site-packages/threatexchange/exchanges/clients/ncmec/hash_api.py", line 36, in nullthrows
    assert v is not None
AssertionError
2022-12-05 12:09:12,190 I] Fetching all fb_threatexchange's configs
Some collabs had errors!
```

**Comment by Dcallies** [comment]
Hey @aokolish, thanks a ton for the report. Looks like there are blank "fingerprints" entries in the newest version of the NCMEC API. We can convert from throwing on them to just filtering them out.

It's also possible the fingerprints field moved elsewhere, the way to check is to ping the schema endpoint directly on the API. 

I'm going to aim to put some time into this tomorrow and see if we can turn a fast minor version around. Will keep in contact.

**Comment by Dcallies** [comment]
The magic line is here: https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py#L139

Looks like maybe there's a tag with no value - so <md5></md5> or somesuch. 

Record starts near 2022-12-02T20:06:59Z

**Comment by Dcallies** [comment]
Okay, got it, the new TMK and videntifier signatures are empty tags:

```
<tmk-pdqf rel="self" href="..."/>
<videntifier rel="self" href="..."/>
```

We could actually provide support for these in the future, but only by doing the downloading of the images inline, which are potentially quite large. Workaround will be to ignore these tags for now.
