### ISSUE TITLE
[hma] Size of hashkey has exceeded the maximum size limit of 2048 bytes

### ISSUE THREAD

**Issue by Dcallies** [facebook/ThreatExchange#1324]
Stack from user on fetcher:
```
[ERROR] ClientError: An error occurred (ValidationException) when calling the Query operation: One or more parameter values were invalid: Size of hashkey has exceeded the maximum size limit of2048 bytes
Traceback (most recent call last):
  File "/var/task/hmalib/lambdas/fetcher.py", line 39, in lambda_handler
    fetcher.run()
  File "/var/task/hmalib/fetching/fetcher.py", line 85, in run
    self._execute_for_collab(collab)
  File "/var/task/hmalib/fetching/fetcher.py", line 184, in _execute_for_collab
    store.flush(checkpoint)
  File "/var/task/hmalib/fetching/bank_store.py", line 199, in flush
    self._handle_upsert(update_key, update_value)
  File "/var/task/hmalib/fetching/bank_store.py", line 246, in _handle_upsert
    return self._handle_delete(key=key)
  File "/var/task/hmalib/fetching/bank_store.py", line 309, in _handle_delete
    member = self.banks_table.get_keyed_bank_member(
  File "/var/task/hmalib/common/models/bank.py", line 864, in get_keyed_bank_member
    return self.get_bank_member(self._key_for_bank(bank_id, member_key))
  File "/var/task/hmalib/common/models/bank.py", line 844, in get_bank_member
    member_keys = self._table.query(
  File "/var/runtime/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/var/runtime/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

Something is being indexed that is too large for dynamodb - likely the indicator string, which can be large for ThreatExchange (1MB, or about 500x too large).

**Comment by Dcallies** [comment]
Source of problem is that the ThreatExchange update key is being passed in unsanitized, which we are currently using the entire indicator + type string combination. If you hit a key type longer than 2048 (i.e. TMK hash), it will barf.

A repo would involve creating a ThreatExchange collab with one TMK. 

This is the offending code: https://github.com/facebook/ThreatExchange/blob/main/hasher-matcher-actioner/hmalib/fetching/bank_store.py#L246

It's trying to remove a record when it notices that it can't handle the signal type, but this is illogical, as:
1. It won't work if you don't see an update, so this attempt was best effort at best
2. We don't support changing signal types at the moment, you need to clear state if you do so, so we can safely assume we never previously ingested.

Fix is to remove the delete attempt and replace with a return with a comment that roughly says a summary of the above.

**Comment by Dcallies** [comment]
A longer term fix would be to use a hash function of some kind on the indicator string if it's longer than some length, but this will be a backwards incompatible change that will require all users to refetch all state. 

Short term filtering out unhandled types will cover most uses, so that's the fix I think we should deploy for now.

**Comment by Dcallies** [comment]
HMA 1.0 is dead as of #1556 !
