### ISSUE TITLE
[py-tx] unable to hash certain PNGs

### ISSUE THREAD

**Issue by prenner** [facebook/ThreatExchange#1708]
when using HMA to hash a PNG via the /hash endpoint, I'm encountering an error 

example url: https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png?20120323050937

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/OpenMediaMatch/blueprints/hashing.py", line 68, in hash_media
    ret[st.get_name()] = st.hash_from_file(path)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/threatexchange/signal_type/signal_base.py", line 196, in hash_from_file
    return cls.hash_from_bytes(file.read_bytes())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/threatexchange/signal_type/pdq/signal.py", line 79, in hash_from_bytes
    pdq_hash, quality = pdq_from_bytes(bytes_)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/threatexchange/signal_type/pdq/pdq_hasher.py", line 30, in pdq_from_bytes
    Image.open(io.BytesIO(file_bytes))
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0xffff603cc9a0>
```

See https://pillow.readthedocs.io/en/stable/PIL.html#PIL.UnidentifiedImageError

**Comment by Dcallies** [comment]
Looks like without the file type hint PIL can't figure out how to decode it. Currently hash_bytes assumes that the file format is not needed, which I know is not true from experience, which is why pytx tends to copy everything into files.

For HMA, we specifically made it so no local tmp files were stored, and so were able to pass file extensions into PIL. We need to figure out how to get PIL to format correctly without passing the original file, which might just involve the right arguments to Open()

**Comment by prenner** [comment]
resolved in https://github.com/facebook/ThreatExchange/pull/1722
