### ISSUE TITLE
[py-tx] Connection Pool is 'sploding

### ISSUE THREAD

**Issue by Dcallies** [facebook/ThreatExchange#359]
Looks like @schatten's comment about pooling was right! https://github.com/urllib3/urllib3/issues/1252

Have to figure out how I patched this over in a previous project:

Traceback (most recent call last):
  File "/home/dcallies/.venv/threatexchange/bin/threatexchange", line 33, in <module>
    sys.exit(load_entry_point('threatexchange', 'console_scripts', 'threatexchange')())
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 149, in main
    execute_command(namespace)
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 87, in execute_command
    command.execute(dataset)
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/cli/fetch.py", line 279, in execute
    consume_descriptors(pending_futures)
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/cli/fetch.py", line 227, in consume_descriptors
    descriptors = item.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/cli/fetch.py", line 319, in _fetch_descriptors
    for td_json in TE.Net.getInfoForIDs(td_ids):
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/TE.py", line 198, in getInfoForIDs
    response = self.getJSONFromURL(url)
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/TE.py", line 126, in getJSONFromURL
    return fb_graph_api.get(url).json()
  File "/home/dcallies/.venv/threatexchange/lib64/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/dcallies/.venv/threatexchange/lib64/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dcallies/.venv/threatexchange/lib64/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/TE.py", line 44, in send
    return super().send(request, **kwargs)
  File "/home/dcallies/.venv/threatexchange/lib64/python3.6/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='graph.facebook.com', port=443): Pool is closed.

**Comment by Dcallies** [comment]
Strangely enough, if I remove the `with` block, then this crash doesn't occur, which makes me think that under the hood, the session object is re-using the same pool in our code, which makes this definitely not work (other solutions might be: thread_localing sessions, always creating new sessions, etc).
